import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import superHubsRouter from "./super-hubs";
import subHubsRouter from "./sub-hubs";
import subHubMenuRouter from "./sub-hub-menu";
import usersRouter from "./users";
import statsRouter from "./stats";
import uploadRouter from "./upload";
import customersRouter from "./customers";
import ordersRouter from "./orders";
import vendorsRouter from "./vendors";
import vendorItemsRouter from "./vendor-items";
import retailInvoicesRouter from "./retail-invoices";
import bankingRouter from "./banking";
import inventoryRouter from "./inventory";
import deliveryReportRouter from "./delivery-report";
import qzRouter from "./qz";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/super-hubs", superHubsRouter);
router.use("/sub-hubs", subHubsRouter);
router.use("/sub-hubs/:id/menu", subHubMenuRouter);
router.use("/users", usersRouter);
router.use("/stats", statsRouter);
router.use("/upload", uploadRouter);
router.use("/customers", customersRouter);
router.use("/orders", ordersRouter);
router.use("/vendors", vendorsRouter);
router.use("/vendor-items", vendorItemsRouter);
router.use("/retail-invoices", retailInvoicesRouter);
router.use("/banking", bankingRouter);
router.use("/inventory", inventoryRouter);
router.use("/delivery-report", deliveryReportRouter);
router.use(qzRouter);

export default router;
